//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeosEnterprise.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeosEnterprise.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura VAT
        ///Oryginał
        ///
        ///Data wystawienia: {{data}}
        ///Termin płatności: {{termin}}
        ///
        ///Sprzedawca:
        ///Geos Enterprise
        ///ul. Adama Mickiewicza 30
        ///30-059 Kraków
        ///NIP: 796-18-10-732
        ///Bank: AMBER GOLD S.A Centrum Rozliczeniowe nr 3
        ///Numer: 0000322228
        ///
        ///Nabywca:
        ///{{klient}}
        ///
        ///Nazwa towaru/usługi:
        ///Naprawa urządzenia elektronicznego
        ///Kwota netto:
        ///{{netto}} zł
        ///Podatek VAT 23%:
        ///{{vat}} zł
        ///Kwota brutto:
        ///{{brutto}} zł
        ///
        ///Fakturę wystawił {{pracownik}} dyrektor Działu Księgowości Geos Enterprise..
        /// </summary>
        internal static string AccountantReport {
            get {
                return ResourceManager.GetString("AccountantReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten dokument jest potwierdzeniem przyjęcia zlecenia naprawy usterki o numerze {{numer_zlecenia}}.
        ///
        ///Nazwa komputera: {{nazwa}}
        ///Numer seryjny komputera: {{nr_seryjny}}
        ///
        ///Zamówienie dla klienta: {{klient}}
        ///
        ///Wstępna wycena: {{koszt}} PLN
        ///
        ///Opis:
        ///{{opis}}
        ///
        ///Zlecenie przyjęte przez {{pracownik}} dnia {{data}}.
        ///
        ///
        ///Dziękujemy za zaufanie!
        ///-Geos Enterprise ©-.
        /// </summary>
        internal static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
    }
}
